site_name: MkDocs Playground

theme:
  name: material

plugins:
  - search
  - mike

extra:
  version:
    provider: mike

nav:
  - 'Introduction': index.md
  - 'Overview':
    - 'CLI Setup': setup-cli.md
    - 'CI Workflow': ci-workflow.md
  - 'Change Log': CHANGELOG.md